CREATE TABLE [dbo].[FORMATO_MENSAJE]
(
	[COD_FORMATO] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[COD_TIPO] INT NOT NULL,
	[COD_TIPO_INFORMACION] INT NOT NULL,
	[NOMBRE] VARCHAR(50) NOT NULL,
	[REMITENTE] VARCHAR(50) NOT NULL,
	[ASUNTO] VARCHAR(50) NOT NULL,
	CONSTRAINT [FK_FORMATO_MENSAJE_TIPO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO] ([COD_TIPO]),
CONSTRAINT [FK_FORMATO_MENSAJE_TIPO_INFORMACION] FOREIGN KEY ([COD_TIPO_INFORMACION]) REFERENCES [dbo].[TIPO_INFORMACION] ([COD_TIPO_INFORMACION])
)
