CREATE TABLE [dbo].[MENSAJE]
(
	[COD_MENSAJE] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[COD_FORMATO] INT NOT NULL,
	[PROYECTO] INT NOT NULL,
	[PRODUCTO] INT NOT NULL,
	CONSTRAINT [FK_MENSAJE_COD_FORMATO] FOREIGN KEY ([COD_FORMATO]) REFERENCES [dbo].[FORMATO_MENSAJE] ([COD_FORMATO]),
	CONSTRAINT [FK_MENSAJE_PRODUCTO_PROYECTO] FOREIGN KEY ([PROYECTO], [PRODUCTO]) REFERENCES [dbo].[PRODUCTO_PROYECTO] ([PROYECTO], [PRODUCTO])
)
