CREATE TABLE [dbo].[PRODUCTO_PROYECTO]
(
	[PROYECTO] INT NOT NULL,
	[PRODUCTO] INT NOT NULL,
	CONSTRAINT [PK_PRODUCTO_PROYECTO] PRIMARY KEY CLUSTERED ([PROYECTO] ASC, [PRODUCTO] ASC),
	CONSTRAINT [FK_PRODUCTO_PROYECTO_PROYECTO] FOREIGN KEY ([PROYECTO]) REFERENCES [dbo].[PROYECTO] ([PROYECTO]),
	CONSTRAINT [FK_PRODUCTO_PROYECTO_PRODUCTO] FOREIGN KEY ([PRODUCTO]) REFERENCES [dbo].[PRODUCTO] ([PRODUCTO])
)
